rust compile failure in next-20260730
+ folks from e5e86df8b666

On Fri, Jul 31, 2026 at 02:28:25PM +0200, Bert Karwatzki wrote:
> With next-20260730 building a kernel with CONFIG_RUST=y fails with
> the following error:
>
>  RUSTC L rust/kernel.o
> error[E0308]: mismatched types
>      --> rust/kernel/sync/poll.rs:175:44
>       |
>   175 |         unsafe { bindings::kvfree_call_rcu((*ptr).rcu.get(), ptr.cast::<ffi::c_void>()) };
>       |                  ------------------------- ^^^^^^^^^^^^^^^^ expected `*mut kvfree_rcu_head`, found `*mut callback_head`
>       |                  |
>       |                  arguments to this function are incorrect
>       |
>       = note: expected raw pointer `*mut bindings::kvfree_rcu_head`
>                  found raw pointer `*mut bindings::callback_head`
> note: function defined here
>      --> /mnt/data/linux-forest/linux-next/rust/bindings/bindings_generated.rs:73708:12
>       |
> 73708 |     pub fn kvfree_call_rcu(head: *mut kvfree_rcu_head, ptr: *mut ffi::c_void);
>       |            ^^^^^^^^^^^^^^^
>
> error: aborting due to 1 previous error
>
> For more information about this error, try `rustc --explain E0308`.
> make[5]: *** [rust/Makefile:781: rust/kernel.o] Fehler 1
> make[4]: *** [Makefile:1420: prepare] Fehler 2
> make[3]: *** [debian/rules:80: build-arch] Fehler 2
>
> Reverting the following commits:
> ef32a74f8f6a ("mm/slab: introduce kfree_rcu_nolock()")
> bdd0cc9f0ffc ("mm/slab: introduce struct kvfree_rcu_head for kvfree_rcu batching")
>
> make the compilation work again.

This is a collision between commit e5e86df8b666 ("rust: poll: use
kfree_rcu() for PollCondVar") in the char-misc tree and the
aforementioned commit bdd0cc9f0ffc ("mm/slab: introduce struct
kvfree_rcu_head for kvfree_rcu batching") in the slab tree.

Something like this avoids the error for me but I am not sure if it is
a proper fix.