Revert: module: Treat dashes and underscores interchangeably in module_blacklist
Build error:
   RUSTC     drivers/gpu/drm/tyr/tyr.o
 error[E0425]: cannot find type `initcall_modname` in crate `::kernel::bindings`
   --> /home/klara/git/linux/drivers/gpu/drm/tyr/tyr.rs:20:1
    |
 20 | / kernel::module_platform_driver! {
 21 | |     type: TyrPlatformDriver,
 22 | |     name: "tyr",
 23 | |     authors: ["The Tyr driver authors"],
 24 | |     description: "Arm Mali Tyr DRM driver",
 25 | |     license: "Dual MIT/GPL",
 26 | | }
    | |_^ not found in `::kernel::bindings`
    |
    = note: this error originates in the macro `$crate::prelude::module` which comes from the expansion of the macro `kernel::module_platform_driver` (in Nightly builds, run with -Z macro-backtrace for more info)

 error[E0422]: cannot find struct, variant or union type `initcall_modname` in crate `::kernel::bindings`
   --> /home/klara/git/linux/drivers/gpu/drm/tyr/tyr.rs:20:1
    |
 20 | / kernel::module_platform_driver! {
 21 | |     type: TyrPlatformDriver,
 22 | |     name: "tyr",
 23 | |     authors: ["The Tyr driver authors"],
 24 | |     description: "Arm Mali Tyr DRM driver",
 25 | |     license: "Dual MIT/GPL",
 26 | | }
    | |_^ not found in `::kernel::bindings`
    |
    = note: this error originates in the macro `$crate::prelude::module` which comes from the expansion of the macro `kernel::module_platform_driver` (in Nightly builds, run with -Z macro-backtrace for more info)

 error: aborting due to 2 previous errors

 Some errors have detailed explanations: E0422, E0425.
 For more information about an error, try `rustc --explain E0422`.

Revert "module: rename module_blacklist to module_denylist"
This reverts commit d678f065fd2d4d6fe30d07aa30821acbba78fed0.
Revert "module: extend module_blacklist parameter to built-in modules"
This reverts commit f4c774ee897af80f0ddb548fc675261ce2caf03e.
Revert "module: treat dashes and underscores interchangeably in module_blacklist"
This reverts commit bc7867a8a8bb3168a28497983ac359720c843df9.