Revert "riscv: Add runtime constant support"
This patch causes the following build failure, regardless of whether
CONFIG_RISCV_ISA_ZBKB is enabled or not:

 /home/klara/git/linux/fs/dcache.c: Assembler messages:
 /home/klara/git/linux/fs/dcache.c:157: Error: attempt to move .org backwards
 /home/klara/git/linux/fs/dcache.c:157: Error: attempt to move .org backwards
 /home/klara/git/linux/fs/dcache.c:157: Error: attempt to move .org backwards
 /home/klara/git/linux/fs/dcache.c:157: Error: attempt to move .org backwards
 /home/klara/git/linux/fs/dcache.c:157: Error: attempt to move .org backwards
 make[3]: *** [/home/klara/git/linux/scripts/Makefile.build:203: fs/dcache.o] Error 1

This reverts commit a44fb5722199de8338d991db5ad3d509192179bb.